server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service7001


    # eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false # 服务器不想自己注册自己
    fetch-registry: false # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
